### ISSUE TITLE
Allow the use of a different base url

### ISSUE THREAD

**Issue by abelmokadem** [micahsnyder/cvdupdate#15]
Current setup automatically goes to database.clamav.net. It would be nice if there is a way to configure the tool so that it can point to a different URL.

**Comment by finchy** [comment]
The tool is made to download from database.clamav.net.  Not another URL

**Comment by abelmokadem** [comment]
If that's the case then so be it. Maybe you should consider removing the URLs from the config file. You have a `config` command, yet you don't support changing this URL. From a user's perspective, this can be frustrating. In the end, it's your project though. Either way, I'm a happy user of this project. Thanks 👍

**Comment by micahsnyder** [comment]
For daily, main, and bytecode this tool is for syncing from the official source (database.clamav.net).  I too don't see much point in allowing you to change the URLs, but you could remove the default databases (`cvd remove --help`) and then add your own (`cvd add --help`).

And you could use `cvd update` to sync additional files from other servers in case you want to sync some unofficial db's with this tool. Take a look at `cvd add --help`.  I haven't done much testing with this, so if there are bugs please let us know and I'll try to fix them as time permits or review PR's as time permits.

There's a related project which probably does a better job with the unofficial databases though.  It is made specifically for this purpose: https://github.com/rseichter/fangfrisch.

**Comment by abelmokadem** [comment]
Thanks a lot for pointing that out @micahsnyder. Will have a look into this tool. I like the idea of being able to pull in different databases using a single tool.
