### ISSUE TITLE
No cvd download verification

### ISSUE THREAD

**Issue by kb1828** [micahsnyder/cvdupdate#3]
I must download updates via a proxy and was sometimes getting truncated cvd files. I had to manually edit the json to force a redownload of the corrupted file.
Can file size or some other validation of the file download be added before adding it to the json as complete?

**Comment by micahsnyder** [comment]
That's a really good idea. I'll try to implement a file size check.

**Comment by kb1828** [comment]
Thanks i discovered that they were truncated by comparing the on disk size to the size printed in the urllib3 debug output.

2021-03-09 13:06:31 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): database.clamav.net:443 
2021-03-09 13:06:32 urllib3.connectionpool DEBUG https://database.clamav.net:443 "GET /daily.cvd?version=26103 HTTP/1.1" 200 105057774

**Comment by kb1828** [comment]
It looks like it should address the issue to me. Should be useful for people on flaky connections as well I think.
Thanks.
