### ISSUE TITLE
Unable to use proxy

### ISSUE THREAD

**Issue by smoeding** [micahsnyder/cvdupdate#7]
I'm using the tool to setup a local mirror in our internal network. The server for the local mirror has no direct internet connection and would need to use the corporate proxy to access external resources. It seems that the cvdupdate tool currently is unable to use a proxy server.

I tried to set environment variables `http_proxy` and `https_proxy` but it did not work.

The [documentation](https://2.python-requests.org/en/latest/api/#module-requests) indicates that `requests.request()` needs an additional `proxies` dictionary to configure a proxy server.

It would be nice to implement this to support local mirrors behind a corporate proxy.

**Comment by goshansp** [comment]
@smoeding have you tried exporting uppercase variable names to your environment? i have not tested this.

export HTTP_PROXY="http://10.10.10.10:8000"
export HTTPS_PROXY="http://10.10.10.10:1212"

**Comment by smoeding** [comment]
Good hint! I tried this but I also get an exception from `urllib3` because the firewall blocks a direct connection. So it does not seem to work using environment variables.

**Comment by kb1828** [comment]
I use a proxy via the http_proxy and https_proxy variables in a an update script with no issues. generally the https_proxy is going to use the CONNECT method. If that is blocked you may have issues.

```
#!/bin/bash

http_proxy=http://proxy-fqdn:3128/
export http_proxy
https_proxy=http://proxy-fqdn:3128/
export https_proxy

/usr/local/python3/bin/cvd update 
```

**Comment by smoeding** [comment]
Ok, my fault...
I was using `sudo` to run the `cvd` command as unprivileged user. But `sudo` ignores the environment from the calling shell. So `cvd` never saw the `https_proxy` environment variable. I'm using `sudo -u mirror http_proxy=http://proxy-fqdn:3128 cvd update` now.
Sorry for the noise! Thanks for your hints!
